#!/bin/bash

source ./set_all_env_vars.sh

echo "USER_ID: ${USER_ID:?}"
echo "PROJECT_ID: ${PROJECT_ID:?}"
echo "REGION: ${REGION:?}"
echo "GCS_BUCKET_NAME: ${GCS_BUCKET_NAME:?}"
echo ""

echo "JAVA_MAIN_CLASS: ${JAVA_MAIN_CLASS:?}"
echo "JAR_FILE_NAME: ${JAR_FILE_NAME:?}"
echo ""

echo "CLASSIC_TEMPLATE_NAME: ${CLASSIC_TEMPLATE_NAME:?}"
echo "FLEX_TEMPLATE_NAME: ${FLEX_TEMPLATE_NAME:?}"
echo "AR_NAME: ${AR_NAME:?}"
echo "AR_LOCATION: ${AR_LOCATION:?}"
echo ""

echo "JAR_FILE_PATH: ${JAR_FILE_PATH:?}"

echo "GCS_PATH: ${GCS_PATH:?}"
echo "CLASSIC_TEMPLATE_LOCATION: ${CLASSIC_TEMPLATE_LOCATION:?}"
echo "FLEX_TEMPLATE_LOCATION: ${FLEX_TEMPLATE_LOCATION:?}"
echo "FLEX_TEMPLATE_IMAGE: ${FLEX_TEMPLATE_IMAGE:?}"
echo ""

echo "PUB_SUB_INPUT_TOPIC: ${PUB_SUB_INPUT_TOPIC:?}"
echo "PUB_SUB_INPUT_SUBSCRIPTION: ${PUB_SUB_INPUT_SUBSCRIPTION:?}"
echo "PUB_SUB_OUTPUT_TOPIC: ${PUB_SUB_OUTPUT_TOPIC:?}"
echo "PUB_SUB_OUTPUT_SUBSCRIPTION: ${PUB_SUB_OUTPUT_SUBSCRIPTION:?}"
echo ""

echo "JOB_NAME_PRODUCER_01: ${JOB_NAME_PRODUCER_01:?}"
echo "JOB_NAME_A: ${JOB_NAME_A:?}"
echo "JOB_NAME_B: ${JOB_NAME_B:?}"
echo ""
